# Define global settings
x-global-settings: &default-extra-configs
  extra_hosts:
    - "es-master-01:192.168.10.1"
    - "es-master-02:192.168.10.2"
    - "es-master-03:192.168.10.3"
  healthcheck:
    test: ["CMD-SHELL", " curl -u elastic:Opense4rch@123 -k https://localhost:9200/_cluster/health || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 5
  ulimits:
    memlock:
      soft: -1
      hard: -1
  deploy:
    resources:
      limits:
        memory: 2g
        cpus: '2'
  networks:
    - es-net

services:
  es-master-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es-master-01
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=Opense4rch@123
      - node.name=es-master-01
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-master-01
      - cluster.initial_master_nodes=es-master-01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es-master-01.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es-master-01.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca.crt
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/es-master-01.key
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/es-master-01.crt
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca.crt
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    <<: *default-extra-configs

  es-master-02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es-master-02
    depends_on:
      es-master-01:
        condition: service_healthy
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g    
      - node.name=es-master-02
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-master-01,es-master-03
      - cluster.initial_master_nodes=es-master-01,es-master-02,es-master-03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es-master-02.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es-master-02.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca.crt
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/es-master-02.key
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/es-master-02.crt
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca.crt
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - esdata02:/usr/share/elasticsearch/data
    <<: *default-extra-configs

  es-master-03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es-master-03
    depends_on:
      es-master-01:
        condition: service_healthy
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=es-master-03
      - cluster.name=es-cluster
      - discovery.seed_hosts=es-master-01,es-master-02
      - cluster.initial_master_nodes=es-master-01,es-master-02,es-master-03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es-master-03.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es-master-03.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca.crt
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/es-master-03.key
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/es-master-03.crt
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca.crt
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - esdata03:/usr/share/elasticsearch/data
    <<: *default-extra-configs

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local

networks:
  es-net:

